experimentName: XRay NAS with SPOS
searchSpaceFile: nni_auto_gen_search_space.json
trialCommand: python tester.py --batch-size 512 --workers 4 --checkpoint ./checkpoints/epoch_99.pth.tar
trialCodeDirectory: /data/jperez/git-python-xray/nni/
trialGpuNumber: 1
trialConcurrency: 3
maxExperimentDuration: 48h
maxTrialNumber: 200
experimentWorkingDirectory: /data/jperez/nni-experiments/
tuner:
  codeDirectory: /data/jperez/git-python-xray/nni/
  className: tuner.EvolutionWithFlops
trainingService:
  platform: local
  useActiveGpu: True
